### PR TITLE
DSpi patches for ncv h-bridge driver

### PR DESCRIPTION
**Pull request by jamesadevine**
@mmoskal I need to neaten this up before merging.

The ncv h-bridge driver requires different spi settings and has a max clock of 5 MHz. I'm reticent to add yet more macros to configure SPI, but it may be required

### CODE REVIEW

**Comment by mmoskal** [comment]
you could add an argument to dspi_init() (lowspeed or something)

**Comment by jamesadevine** [comment]
Yeah, cpol and cpha too...

**Comment by mmoskal** [comment]
I have not yet encountered a device where you have to change these from 0/0, but I suppose they exist.

**Comment by jamesadevine** [comment]
Errr this h-bridge driver requires CPHA = 1

**Pull request merged**
